### ISSUE TITLE
[Test] Allowing/expecting a test case to fail/panic

### ISSUE THREAD

**Issue by m-Peter** [onflow/cadence-tools#108]
### Issue To Be Solved
Currently, there is no way to specify that a test is expected to fail/panic. For example:

```bash
flow test --cover MerkleProof_test.cdc
Running tests...

Test results: "MerkleProof_test.cdc"
- PASS: testVerifyValidProof
- FAIL: testVerifyInvalidProof
		Execution failed:
			error: panic: invalid proof
			  --> ./contracts/MerkleProof.cdc:12:16
			
- PASS: testVerifyProofWithLowerLeaf
- PASS: testVerifyWithHigherLeaf
Coverage: 100.0% of statements
```
For the `testVerifyInvalidProof` test case, the `error: panic: invalid proof` is the expected program behavior, however the test case is marked with a `FAIL` status.

### Suggest A Solution

Add a built-in method/matcher, which wraps a method call execution and expects a panic with a certain error message.

```cadence
Test.assertFailsWith(fun(): Void {
    merkleProof.verifyProof(
        proof: [proof.decodeHex()],
        root: root.decodeHex(),
        leaf: leaf.decodeHex(),
        hasherRawValue: 1
    )
}, "invalid proof")
```
  
### Context

https://github.com/onflow/developer-grants/issues/148

**Comment by m-Peter** [comment]
cc @SupunS @turbolent 
Correct me if I'm wrong, but other than running this through a script and verifying that the `ResultStatus` is `failed`, I didn't find any other way.

**Comment by SupunS** [comment]
> Add a built-in method/matcher, which wraps a method call execution and expects a panic with a certain error message.
> 
> ```cadence
> Test.assertFailsWith(fun(): Void {
>     merkleProof.verifyProof(
>         proof: [proof.decodeHex()],
>         root: root.decodeHex(),
>         leaf: leaf.decodeHex(),
>         hasherRawValue: 1
>     )
> }, "invalid proof")
> ```

This sounds like a nice solution! 👌

Maybe the name of the function could be something like `expectFailure()`.

Going one step further, we could probably make the second parameter accept another string-matcher (rather than a string), so we could also support asserts like contains/startsWith/etc., for the error message. But of course, doesn't need to be in the first iteration, maybe a future improvement.
