### ISSUE TITLE
Need cadence.server.parseContractInitializerParameters

### ISSUE THREAD

**Issue by bthaile** [onflow/cadence-tools#129]
Tool: Cadence Language Server

### Issue To Be Solved
There is two commands to get the parameters 
 - cadence.server.getContractInitializerParameters
 - cadence.server.getEntryPointParameters
 
and one command to parse the parameters (for transactions and scripts)
 - cadence.server.parseEntryPointArguments

Needed a parse command for contracts Initializer Parameters.

### (Optional): Suggest A Solution
I see two options:
1. Create a fourth command for parsing contracts initialization parameters
2. Remove the contract specific command and use entry point commands for contracts as well as transactions and scripts. 
  
### (Optional): Context
Working on supporting contract initialization parameters in playground. The issue is an old one but keeps being requested by the community. 

Playground Issues:
https://github.com/onflow/flow-playground/issues/18
https://github.com/onflow/flow-playground/issues/596

**Comment by turbolent** [comment]
The first option sounds good and would "complete" the current set of functions. Adding it should be pretty easy, and maybe along the way the code of `parseEntryPointArguments` can be factored out and reused.

I don't quite get what is meant with the second option, could you please elaborate?

**Comment by bthaile** [comment]
The second option would remove "cadence.server.getContractInitializerParameters"
and only have "cadence.server.getEntryPointParameters" and "cadence.server.parseEntryPointArguments"

and have contract `init` be included in what an EntryPoint is for contracts. Therefore only need two commands to handle contracts, transactions and scripts.

**Comment by turbolent** [comment]
Ah, I see! That makes sense and seems even better than the first option 👍
