### ISSUE TITLE
[Test] Stacktrace doesn't use filenames for test files

### ISSUE THREAD

**Issue by jribbink** [onflow/cadence-tools#254]
### Current Behavior

When an error is returned for a location in a test file, the location of the file in the stack trace is hard to understand.  I.e. it should be `test_mytest.cdc` instead of a string of numbers

![Screenshot 2023-12-01 at 12 19 00 PM](https://github.com/onflow/cadence-tools/assets/17958158/f31b363f-4be9-486e-94f9-41e59713b640)

### Expected Behavior

Align the name of the file with the actual system filename

### Steps To Reproduce

Create an error inside of a test file

### Environment

```markdown
- Cadence version: 0.32.5
- Network: Test framework
```

**Comment by m-Peter** [comment]
@jribbink Nice idea :clap:
