### ISSUE TITLE
[Suggestion] Why no mention of Cadence prettier tool?

### ISSUE THREAD

**Issue by bartolomej** [onflow/cadence-tools#257]
I was searching if there are any existing code formatting tools for Cadence, so I figured this repo is the one where such a tool would probably live.

That wasn't the case, so after some more searching I found that the current prettier tool lives here atm: https://github.com/turbolent/prettier

Should we at least mention or link to that repo within this repo's README file to make it easier to discover?

But maybe that tool isn't "production ready" yet and there is still more work to be done before making it available to Cadence users (based on https://github.com/onflow/cadence/issues/209).

**Comment by turbolent** [comment]
Sorry for the confusion here: Though the code formatting functionality is being developed in the Cadence codebase / repository, there's no tool for it yet that a developer could use to format their Cadence code.

https://github.com/turbolent/prettier is a Go library for formatting, it is not a tool, it is only a building block that is used in Cadence to implement the code formatting functionality.

The closest to a tool we have to try out the code formatting functionality is the _internal_ https://github.com/onflow/cadence/tree/master/tools/pretty. As the README says, for now it is just there to assist contributors working on the implementation of the Cadence code formatter, it is not meant for Cadence developers. However, once the code formatting functionality is complete, we can take this internal tool, move it into this repo, and turn it into something a typical Cadence developer could use, and finally integrate it into the CLI and other tools like the language server and VS Code extension.
