### ISSUE TITLE
[LS] getAuthAccount is not supported

### ISSUE THREAD

**Issue by justinbarry** [onflow/cadence-tools#62]
### Problem

<img width="774" alt="image" src="https://user-images.githubusercontent.com/328965/180825201-d3555401-c474-4883-b113-386cc3ec6c87.png">

### Steps to Reproduce

Open a cadence script and attempt to use the built in `getAuthAccount` function. 

### Acceptance Criteria

No more red squiggly line.

### Context

Using version v0.7.1 of the Cadence extension.

<img width="523" alt="image" src="https://user-images.githubusercontent.com/328965/180825796-143115ac-fd54-4206-af26-1f8b18912f30.png">

**Comment by ashlinSajan** [comment]
> You can't access `getAuthAccount` in scripts, you can only do that in transactions https://docs.onflow.org/cadence/language/accounts/#authaccount

Hi @sideninja This is my code
export const setupUserTx = `
import MyNFT from 0x8469322b1f3482d1
import NonFungibleToken from 0x631e88ae7f1d7c20
import FungibleToken from 0x9a0766d93b6608b7
import FlowToken from 0x7e60df042a9c0868
import NFTMarketplace from 0x8469322b1f3482d1
//const account1 = getAuthAccount(0x8469322b1f3482d1)
transaction {
  prepare(acct:AuthAccount) {
     log(acct)
     let acct = getAuthAccount(0x8469322b1f3482d1)
    acct.save(<- MyNFT.createEmptyCollection(), to: /storage/MyNFTCollection)
    acct.link<&MyNFT.Collection{MyNFT.CollectionPublic, NonFungibleToken.CollectionPublic}>(/public/MyNFTCollection, target: /storage/MyNFTCollection)
    acct.link<&MyNFT.Collection>(/private/MyNFTCollection, target: /storage/MyNFTCollection)

    let MyNFTCollection = acct.getCapability<&MyNFT.Collection>(/private/MyNFTCollection)
    let FlowTokenVault = acct.getCapability<&FlowToken.Vault{FungibleToken.Receiver}>(/public/flowTokenReceiver)

    acct.save(<- NFTMarketplace.createSaleCollection(MyNFTCollection: MyNFTCollection, FlowTokenVault: FlowTokenVault), to: /storage/MySaleCollection)
    acct.link<&NFTMarketplace.SaleCollection{NFTMarketplace.SaleCollectionPublic}>(/public/MySaleCollection, target: /storage/MySaleCollection)
  }

  execute {
    log("A user stored a Collection and a SaleCollection inside their account")
  }
}
Getting the error 
 let acct = getAuthAccount(0x8469322b1f3482d1)
   |                 ^^^^^^^^^^^^^^ not found in this scope

**Comment by sideninja** [comment]
@ashlinSajan what tool you used to write the code? VSCode, Playground...?

**Comment by ashlinSajan** [comment]
> @ashlinSajan what tool you used to write the code? VSCode, Playground...?

I actually use the flow cli to deploy my contracts and is using the react frontend to interact with the transaction code added above.

**Comment by ashlinSajan** [comment]
> @ashlinSajan what tool you used to write the code? VSCode, Playground...?

![UI_bug](https://user-images.githubusercontent.com/34328137/221494735-86882411-8298-4a97-9e48-ad2b04928c13.JPG)
The error I received in the frontend from the transaction code

**Comment by bluesign** [comment]
getAuthAccount is available only in scripts, you should use acct from `prepare(acct:AuthAccount)`  to access authorizers.
