### ISSUE TITLE
[LS] Support for resolving access(account)

### ISSUE THREAD

**Issue by Bamthelearner** [onflow/cadence-tools#65]
Currently, when we use access modifier access(account), vscode extention will treat all these contracts to be deployed in separate accounts and report error.

As the contracts should already be defined in flow.json, it should be possible to resolve whether the contracts are going to be under the same account?

Adding this feature can help a lot!
Thank you.

**Comment by sideninja** [comment]
@Bamthelearner @turbolent this is now implemented.
