### ISSUE TITLE
[Test] Improve test failure output

### ISSUE THREAD

**Issue by sideninja** [onflow/cadence-tools#93]
Currently when the `Test.assert` function fails it doesn't provide much output besides the `error: assertion failed` which makes it hard to debug and know what the issue is. 

I believe the output of assert function should be improved to be more like:
```
error: not equal, expected value: 1, actual value: 2, both values should be equal
```

**Comment by m-Peter** [comment]
@sideninja Good idea :+1: We are currently making improvements to the Cadence Testing Framework, as part of this grant proposal https://github.com/onflow/developer-grants/issues/148. We'll keep that in mind, as a low-hanging fruit. We have already started active development on it, with https://github.com/onflow/cadence/pull/2420
